
/*Initial temp data for Customers Only.*/

INSERT INTO table VALUES ('Sanders','Cassandra','Jackson@dis.gov','Green River','Norway');
INSERT INTO table VALUES ('Keller','Alice','Guinevere@nec.org','Carolina','South Africa');
INSERT INTO table VALUES ('Ballard','Chastity','Acton@vestibulum.org','Seaford','Nepal');
INSERT INTO table VALUES ('Allison','Lee','Leila@aliquam.com','Stevens Point','Switzerland');
INSERT INTO table VALUES ('Paul','Drake','Keane@Proin.com','Appleton','Argentina');
INSERT INTO table VALUES ('Holmes','Tate','Hadassah@est.com','Helena','Micronesia');
INSERT INTO table VALUES ('Harrell','Angelica','Vance@sit.net','Eugene','Antarctica');
INSERT INTO table VALUES ('Mckay','Lacey','Alec@malesuada.us','Webster Groves','Ecuador');
INSERT INTO table VALUES ('Alvarado','Nora','Duncan@torquent.com','Easthampton','Marshall Islands');
INSERT INTO table VALUES ('Hays','Melodie','Elton@placerat.net','Kansas City','El Salvador');
INSERT INTO table VALUES ('Newman','Xantha','Rhea@nascetur.edu','Vernon','Brunei Darussalam');
INSERT INTO table VALUES ('Noel','Amos','Mira@Etiam.gov','Sandpoint','New Zealand');
INSERT INTO table VALUES ('Woodard','Damon','Kessie@scelerisque.us','Pittston','Georgia');
INSERT INTO table VALUES ('Justice','Ronan','Wyatt@urna.org','Fitchburg','United Kingdom');
INSERT INTO table VALUES ('Carlson','Randall','Raya@eleifend.gov','Texas City','Guyana');
INSERT INTO table VALUES ('Golden','Jaden','Cooper@semper.org','Eau Claire','Chile');
INSERT INTO table VALUES ('Melton','Grace','Robert@nibh.edu','Parma','Saint Helena');
INSERT INTO table VALUES ('Hughes','William','Isadora@rutrum.us','Clemson','Senegal');
INSERT INTO table VALUES ('Payne','Rebecca','Byron@volutpat.edu','Cairo','Somalia');
INSERT INTO table VALUES ('Welch','Tanek','Christian@in.us','Macomb','Tajikistan');
INSERT INTO table VALUES ('Herring','Noah','Yoshio@quam.com','Huntsville','Spain');
INSERT INTO table VALUES ('Owen','Drew','Graham@Duis.gov','Irvine','Mauritius');
INSERT INTO table VALUES ('Myers','Mohammad','Jana@conubia.org','Huntington Beach','Liberia');
INSERT INTO table VALUES ('Blake','Demetrius','Sigourney@auctor.gov','Valparaiso','Viet Nam');
INSERT INTO table VALUES ('Giles','Harriet','Cade@congue.net','Lowell','Pakistan');
INSERT INTO table VALUES ('Dennis','Keiko','Hammett@gravida.gov','Elko','Malta');
INSERT INTO table VALUES ('Bryan','Garrett','Calvin@netus.edu','Bandera','Marshall Islands');
INSERT INTO table VALUES ('Leon','Hoyt','Hamilton@ut.net','Galveston','Djibouti');
INSERT INTO table VALUES ('Harper','Arsenio','Melodie@odio.edu','Boston','Guyana');
INSERT INTO table VALUES ('Dyer','Gannon','Erich@dui.us','Opelousas','Saudi Arabia');
INSERT INTO table VALUES ('Mcpherson','Ori','Petra@a.edu','Frankfort','Puerto Rico');
INSERT INTO table VALUES ('Wilson','Alec','Colby@enim.com','Superior','Benin');
INSERT INTO table VALUES ('Sims','Brennan','Ori@accumsan.org','Nacogdoches','Ukraine');
INSERT INTO table VALUES ('Hutchinson','Kelsie','Ina@porttitor.edu','Martinsburg','Costa Rica');
INSERT INTO table VALUES ('Trevino','Lara','Alexis@sed.com','Claremore','Jordan');
INSERT INTO table VALUES ('Hurst','Audrey','Octavia@dignissim.com','Leominster','Mongolia');
INSERT INTO table VALUES ('Fry','Xantha','Quin@diam.edu','Roanoke','San Marino');
INSERT INTO table VALUES ('Mullins','Stephanie','Vaughan@dui.us','Hickory','Solomon Islands');
INSERT INTO table VALUES ('Hyde','Ashton','Chelsea@turpis.com','Vernon','Togo');
INSERT INTO table VALUES ('Forbes','Ishmael','Serena@condimentum.net','Dalton','Uganda');
INSERT INTO table VALUES ('Reid','Jael','Geoffrey@est.com','Guánica','Maldives');
INSERT INTO table VALUES ('Rosario','Richard','Gareth@cubilia.net','Hidden Hills','Botswana');
INSERT INTO table VALUES ('Massey','Salvador','Vaughan@elementum.edu','Gardner','Saint Lucia');
INSERT INTO table VALUES ('Gentry','Margaret','Macy@bibendum.edu','Auburn','Finland');
INSERT INTO table VALUES ('Wiggins','Gray','MacKensie@dictum.net','Cape Coral','Sweden');
INSERT INTO table VALUES ('Phillips','Leilani','Reese@augue.com','Truth or Consequences','Micronesia');
INSERT INTO table VALUES ('Phillips','Latifah','Vaughan@vel.edu','Schaumburg','United States Minor Outlying Islands');
INSERT INTO table VALUES ('Miller','Bree','Wynne@congue.gov','South Pasadena','Armenia');
INSERT INTO table VALUES ('Ray','Amber','Vaughan@fringilla.net','Cruz Bay','Reunion');
INSERT INTO table VALUES ('Doyle','Vivian','Wade@euismod.com','Maywood','Cyprus');
INSERT INTO table VALUES ('Riddle','Medge','Giselle@condimentum.net','Sault Ste. Marie','Austria');
INSERT INTO table VALUES ('Tate','Kane','Ferris@In.net','Peekskill','Saint Lucia');
INSERT INTO table VALUES ('Nicholson','Cullen','Levi@semper.us','Lake Forest','Albania');
INSERT INTO table VALUES ('Brewer','Rajah','Ivana@scelerisque.net','Galesburg','Malawi');
INSERT INTO table VALUES ('Diaz','Mona','Ciaran@accumsan.org','Ogden','Germany');
INSERT INTO table VALUES ('Johnson','Althea','Abraham@vulputate.net','Huntsville','Samoa');
INSERT INTO table VALUES ('Blackburn','Bruce','Julian@inceptos.gov','Areceibo','Jamaica');
INSERT INTO table VALUES ('Franklin','Salvador','India@gravida.org','Delta Junction','Peru');
INSERT INTO table VALUES ('Sanchez','Macey','Wyoming@risus.org','Hollister','Romania');
INSERT INTO table VALUES ('Hancock','Sonia','Wanda@mattis.gov','Opelousas','Mexico');
INSERT INTO table VALUES ('Lopez','Harding','Liberty@condimentum.net','West Springfield','Haiti');
INSERT INTO table VALUES ('Rosario','Curran','Ivan@aliquam.org','Brea','San Marino');
INSERT INTO table VALUES ('Alston','Dora','Maxwell@Curabitur.edu','Chester','India');
INSERT INTO table VALUES ('Erickson','Malik','Cyrus@Lorem.us','Worland','Uruguay');
INSERT INTO table VALUES ('Wolf','Mufutau','Cassady@eleifend.com','Tamuning','Pitcairn');
INSERT INTO table VALUES ('Gallagher','Sacha','Aiko@dignissim.org','Bakersfield','Christmas Island');
INSERT INTO table VALUES ('Kinney','Macy','Wynne@Class.gov','Louisville','Switzerland');
INSERT INTO table VALUES ('Deleon','Amy','Jorden@sollicitudin.us','Highland Park','South Georgia and The South Sandwich Islands');
INSERT INTO table VALUES ('Burt','Emmanuel','Chaim@lectus.us','Olympia','Falkland Islands (Malvinas)');
INSERT INTO table VALUES ('Adams','Sydnee','Chase@nonummy.net','Bentonville','South Africa');
INSERT INTO table VALUES ('Johnston','Neve','Walter@Maecenas.org','Dodge City','French Southern Territories');
INSERT INTO table VALUES ('Riggs','Kirk','Xandra@sagittis.net','Montpelier','United States Minor Outlying Islands');
INSERT INTO table VALUES ('Barber','Jescie','Noah@rutrum.edu','La Palma','Russian Federation');
INSERT INTO table VALUES ('Mcfarland','Fay','Aimee@parturient.org','Tacoma','Ethiopia');
INSERT INTO table VALUES ('Moore','Fitzgerald','Ronan@tellus.org','Rancho Cordova','Benin');
INSERT INTO table VALUES ('Case','Orli','Velma@aliquet.gov','Shawnee','Bolivia');
INSERT INTO table VALUES ('Horne','Courtney','Kelly@nunc.us','Cape May','Kazakhstan');
INSERT INTO table VALUES ('Stone','Lawrence','Janna@aliquet.us','Bismarck','Mozambique');
INSERT INTO table VALUES ('Hickman','Preston','Heidi@sociis.us','Sonoma','Tokelau');
INSERT INTO table VALUES ('Merritt','Ramona','Armand@Aliquam.us','Monterey','Finland');
INSERT INTO table VALUES ('Fields','Avye','Renee@rhoncus.com','Brockton','Algeria');
INSERT INTO table VALUES ('Romero','Aladdin','Hoyt@Nunc.gov','Syracuse','San Marino');
INSERT INTO table VALUES ('Richard','Thane','Abdul@Phasellus.gov','Fitchburg','Macedonia');
INSERT INTO table VALUES ('Atkins','Carter','Aphrodite@mi.us','Malibu','Senegal');
INSERT INTO table VALUES ('Sweet','Hope','Sylvester@placerat.us','East Rutherford','Antigua and Barbuda');
INSERT INTO table VALUES ('Booker','Harlan','Mason@pellentesque.us','Perth Amboy','Aruba');
INSERT INTO table VALUES ('Fuentes','Camille','Glenna@hymenaeos.net','Brown Deer','Suriname');
INSERT INTO table VALUES ('Cunningham','Dawn','Jameson@tempus.gov','Ventura','Holy See (Vatican City State)');
INSERT INTO table VALUES ('Carroll','Steel','Colleen@posuere.us','Radford','Czech Republic');
INSERT INTO table VALUES ('Dotson','Lawrence','Hamilton@varius.net','Monterey Park','Solomon Islands');
INSERT INTO table VALUES ('Collins','Quon','Zeus@aptent.org','Covina','Guam');
INSERT INTO table VALUES ('Reilly','Lane','Kimberley@facilisi.com','Jordan Valley','Greece');
INSERT INTO table VALUES ('Contreras','Kirk','Ocean@risus.us','Claremont','Saint Vincent and The Grenadines');
INSERT INTO table VALUES ('Barry','Bruno','Beatrice@rhoncus.com','Deadwood','Heard Island and Mcdonald Islands');
INSERT INTO table VALUES ('Whitley','Charde','Graham@massa.edu','Georgetown','Mauritania');
INSERT INTO table VALUES ('Flynn','Shellie','Andrew@malesuada.com','Lowell','Belarus');
INSERT INTO table VALUES ('Peterson','Susan','Theodore@nunc.org','College Park','Korea, Republic of');
INSERT INTO table VALUES ('Phelps','Patrick','Mara@Fusce.gov','Huntington','Thailand');
INSERT INTO table VALUES ('Henson','Shay','Candace@nunc.org','Rapid City','Papua New Guinea');
INSERT INTO table VALUES ('Gillespie','Emerson','Timothy@Suspendisse.gov','Flint','Hungary');
